spring.application.name=ms-products

# Configuracion de conexion mysql
spring.datasource.url=jdbc:mysql://localhost:3306/products_ms?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=L192380346-2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
