INSERT INTO products (name, description, price, stock, active) VALUES
                                                                   ('Teclado Mecánico RGB', 'Teclado mecánico con switches azules y retroiluminación RGB', 89.99, 45, 1),
                                                                   ('Mouse Inalámbrico Ergonómico', 'Mouse óptico inalámbrico con 6 botones programables', 34.50, 120, 1),
                                                                   ('Monitor 27" 4K IPS', 'Monitor UHD 4K con panel IPS y HDR10', 349.00, 18, 1),
                                                                   ('Auriculares con Cancelación de Ruido', 'Auriculares over-ear Bluetooth con ANC activa', 129.90, 60, 1),
                                                                   ('Webcam Full HD 1080p', 'Webcam con micrófono estéreo y enfoque automático', 59.99, 80, 1),
                                                                   ('Hub USB-C 7 en 1', 'Hub con HDMI, USB 3.0, SD y carga rápida PD', 45.00, 200, 1),
                                                                   ('SSD NVMe 1TB', 'Unidad de estado sólido PCIe Gen4 hasta 7000 MB/s', 99.99, 75, 1),
                                                                   ('Memoria RAM DDR5 16GB', 'Módulo DDR5 5600MHz para escritorio', 74.90, 90, 1),
                                                                   ('Cargador Inalámbrico 15W', 'Cargador Qi compatible con iPhone y Android', 24.99, 150, 1),
                                                                   ('Funda para Laptop 15.6"', 'Funda acolchada resistente al agua', 19.99, 300, 1),
                                                                   ('Silla Gamer Ergonómica', 'Silla reclinable con soporte lumbar ajustable', 219.00, 12, 1),
                                                                   ('Escritorio Ajustable en Altura', 'Escritorio eléctrico sit-stand con memoria de posiciones', 399.00, 8, 1),
                                                                   ('Micrófono Condensador USB', 'Micrófono cardioide para streaming y podcasts', 79.99, 40, 1),
                                                                   ('Control Inalámbrico Pro', 'Mando con gatillos adaptativos y haptics', 69.99, 55, 1),
                                                                   ('Tablet Gráfica 10x6"', 'Tableta digitalizadora con lápiz sensible a presión', 64.50, 35, 1),
                                                                   ('Router WiFi 6 AX3000', 'Router dual band con MU-MIMO y OFDMA', 119.00, 25, 1),
                                                                   ('Disco Duro Externo 2TB', 'HDD portátil USB 3.2 con cifrado por hardware', 69.99, 100, 1),
                                                                   ('Cable HDMI 2.1 2m', 'Cable Ultra High Speed 8K/4K@120Hz', 15.99, 500, 1),
                                                                   ('Lámpara LED de Escritorio', 'Lámpara con 5 niveles de brillo y temperatura de color', 29.99, 110, 1),
                                                                   ('Soporte Monitor Brazo Articulado', 'Brazo de gas para monitores de 17" a 32"', 49.90, 65, 1),
                                                                   ('Impresora Multifuncional Inkjet', 'Imprime, escanea y copia con WiFi y dúplex', 149.00, 20, 1),
                                                                   ('Power Bank 20000mAh', 'Batería externa con carga rápida 22.5W y pantalla LED', 39.99, 140, 1),
                                                                   ('Smartwatch Deportivo', 'Reloj con GPS, SpO2 y monitor cardíaco', 159.99, 48, 1),
                                                                   ('Altavoz Bluetooth Portátil', 'Altavoz IPX7 resistente al agua con 20h de batería', 54.99, 95, 1),
                                                                   ('Adaptador DisplayPort a HDMI', 'Convertidor 4K@60Hz plug and play', 12.99, 250, 1),
                                                                   ('Teclado Anterior Retirado', 'Modelo descatalogado sustituido por la v2', 49.99, 0, 0),
                                                                   ('Mouse Óptico Básico', 'Modelo antiguo con cable USB-A', 9.99, 0, 0),
                                                                   ('Pantalla CRT 15" Legada', 'Monitor retirado del catálogo por obsolescencia', 30.00, 0, 0),
                                                                   ('Tarjeta Gráfica GTX Serie Vieja', 'GPU retirada, sin stock disponible', 199.00, 0, 0),
                                                                   ('Funda de Cuero Premium (Edición Limitada)', 'Accesorio de edición limitada ya agotado', 89.00, 0, 0);